package com.gallantrealm.modsynth;

import java.util.HashMap;
import com.gallantrealm.android.Translator;

public class ModSynthTranslator extends Translator {

	HashMap<String, String> trans;

	@Override
	public String translateSpanish(String text) {
		if (trans == null) {
			trans = new HashMap();
			trans.put("ModSynth", "ModSynth");
			trans.put("Synthesizer", "Sintetizador");
			trans.put("polyphonic, modular, unlimited", "polifónico, modular, ilimitado");
			
			// Translations for main panel
			trans.put("Instrument", "Instrumento");
			trans.put("Sound", "Sonar");
			trans.put("Harmonics", "Armónicos");
			trans.put("Filter", "Filtro");
			trans.put("Amp", "Amp");
			trans.put("Mod", "Mod");
			trans.put("Mod2", "Mod2");
			trans.put("Echo", "Echo");
			trans.put("Arpeggio", "Arpegio");
			trans.put("Sequencer", "Secuenciador");
			trans.put("Record", "Grabar");
			trans.put("Type", "Clase");
			trans.put("Shape", "Forma");
			trans.put("Amount", "Cantidad");
			trans.put("Rate", "Tasa");
			trans.put("Sync", "Sinc");
			trans.put("Attack", "Ataque");
			trans.put("Decay", "Decaimiento");
			trans.put("Sustain", "Sostenido");
			trans.put("Release", "Relajación");
			trans.put("Save", "Guardar");
			trans.put("Save Recording", "Guardar grabación");
			trans.put("Recording name:", "Grabación nombre:");
			trans.put("Saved to", "Guardado en");
			trans.put("Failed to save to", "No se pudo guardar a");
			trans.put("Send", "Enviar");
			trans.put("Delete", "Eliminar");
			trans.put("Voices", "Voces");
			trans.put("Mono", "Mono");
			trans.put("Poly", "Poli");
			trans.put("Chorus", "Coro");
			trans.put("Chorus Width", "Ancho Coro");
			trans.put("Portamento", "Portamento");
			trans.put("Velocity", "Velocidad");
			trans.put("Expression", "Expresión");
			trans.put("Octave", "Octava");
			trans.put("Hold", "Mantener");
			trans.put("Key", "Clave");
			trans.put("Resonance", "Resonancia");
			trans.put("Range", "Rango");
			trans.put("low", "bajo");
			trans.put("high", "alto");
			trans.put("Volume", "Volumen");
			trans.put("Overdrive", "Overdrive");
			trans.put("per Voice", "por Voz");
			trans.put("Amount", "Cantidad");
			trans.put("Delay", "Delay");
			trans.put("Feedback", "Realimentación");
			trans.put("Flange", "Flange");
			trans.put("Rate", "Tasa");
			trans.put("Glide", "Glide");
			trans.put("Note", "Nota");
			trans.put("Loop", "Loop");
			trans.put("bpm", "bpm");
			trans.put("Up", "Arriba");
			trans.put("Down", "Abajo");
			trans.put("Record", "Grabar");
			trans.put("Stop", "Parar");
			trans.put("Replay", "Repetir");

			trans.put("None", "Nada");
			trans.put("Both", "Ambos");
			trans.put("Vibrato", "Vibrato");
			trans.put("Pitch", "Tono");
			trans.put("Volume+Filter", "Volumen + Filtro");
			trans.put("C", "Do");
			trans.put("Db", "Re bemol");
			trans.put("D", "Re");
			trans.put("Eb", "Mi bemol");
			trans.put("E", "Mi");
			trans.put("F", "Fa");
			trans.put("Gb", "Sol bemol");
			trans.put("G", "Sol");
			trans.put("Ab", "La bemol");
			trans.put("A", "La");
			trans.put("Bb", "Si bemol");
			trans.put("B", "Si");
			trans.put("Low Pass", "Paso bajo");
			trans.put("Band Pass", "Paso de banda");
			trans.put("High Pass", "Paso alto");
			trans.put("Fade", "Fundido");
			trans.put("Comb 1", "Peine 1");
			trans.put("Comb 2", "Peine 2");
			trans.put("Comb 3", "Peine 3");
			trans.put("Comb 4", "Peine 4");
			trans.put("Formant 1", "Formantes 1");
			trans.put("Formant 2", "Formantes 2");
			trans.put("Formant 3", "Formantes 3");
			trans.put("Formant 4", "Formantes 4");
			trans.put("Wave", "Ola");
			trans.put("Ramp Up", "Rampa hacia arriba");
			trans.put("Ramp Down", "Rampa hacia abajo");
			trans.put("Two Tone", "Dos tonos");
			trans.put("Noise", "Ruido");
			trans.put("Pulse 1/4", "Pulso 1/4");
			trans.put("Pulse 1/8", "Pulso 1/8");
			trans.put("Pulse 1/16", "Pulso 1/16");
			trans.put("Mod Pitch", "Mod el tono");
			trans.put("Mod Amp", "Mod la amp");

			trans.put("Save sound as", "Guardar sonido");
			trans.put("Delete sound?", "¿Eliminar sonido?");
			trans.put("Are you sure you want to quit?", "¿Seguro que quieres salir?");
			trans.put("Save Recording", "Guardar grabación");
			trans.put("Recording name:", "Nombre de la grabación:");

			// translations for settings panel
			trans.put("Settings", "Ajustes");
			trans.put("Keyboard size", "Tamaño del teclado");
			trans.put("Background", "Fondo");
			trans.put("Choose", "Escoger");
			trans.put("MIDI channel", "MIDI canal");
			trans.put("Tuning type", "Clase de afinar");
			trans.put("Tuning cents", "Afinar en cents");
			trans.put("Any", "Cualquier canal");
			trans.put("Equal Temperament", "Temperamento igual");
			trans.put("Just Intonation", "Entonación justo");
			trans.put("Out of Tune", "Fuera de tono");
			trans.put("Choose a background", "Elija un fondo");
			trans.put("Onyx", "Onyx");
			trans.put("Metal", "Metal");
			trans.put("Wood", "Leña");
			trans.put("Aura", "Aura");
			trans.put("Ice", "Helado");
			trans.put("Tea", "Té");
			trans.put("Space", "Espacio");
			trans.put("Sunset", "Puesta de sol");
			trans.put("Tropical", "Tropical");

			// modsynth specific
			trans.put("Library", "Biblioteca");
			trans.put("Get Full Version", "Obten la versión completa");
			trans.put("Add Module", "Añadir módulo");
			trans.put("Delete Module", "Eliminar módulo");
			trans.put("Delete module?", "¿Eliminar módulo?");
			trans.put("Edit", "Editar");
			trans.put("Edit >>", "Editar >>");
			trans.put("Start", "Iniciar");
			trans.put("Done", "Hecho");
			trans.put("No module selected.", "Sin módulo seleccionado");
			trans.put("Full Version", "Versión completa");
			trans.put("Add FM Operators, spectral filtering, PCM synthesis, harmonic editing and more with ModSynth full version!", 
					"¡Agregue los operadores de FM, el filtrado espectral, la síntesis de PCM, la edición armónica y más con la versión completa de ModSynth!");
			trans.put("Buy", "Comprar");
			trans.put("Later", "Luego");
			trans.put("Sample rate", "Frecuencia de muestreo");
			trans.put("Tuning", "Sintonización");
			trans.put("Wave Form", "Forma de onda");
			trans.put(">>", ">>");
			trans.put("Detune", "Desafinación");
			trans.put("Modulation", "Modulación");
			trans.put("<< Done", "<< Hecho");
			trans.put("on Glide", "Deslizamiento");
			trans.put("Slope", "Declive");
			trans.put("Tone", "Tono");
			trans.put("Select module", "Seleccione el módulo");
			trans.put("Envelope", "Envolvente");
			trans.put("Mixer", "Mezclador");
			trans.put("Oscillator", "Oscilador");
			trans.put("Pad", "Pad");
			trans.put("Keyboard", "Teclado");
			trans.put("Output", "Salida");
			trans.put("Blue", "Azul");
			trans.put("Green", "Verde");
			trans.put("Circuit", "Circuito");
			trans.put("Save instrument as", "Ahorre instrumento");
			trans.put("Delete instrument?", "¿Eliminar instrumento?");
			trans.put("You cannot delete this instrument.", "No puede eliminar este instrumento.");
			trans.put("Operator", "Operador");
			trans.put("MultiOsc", "MúltiOsc");
			trans.put("PCM", "PCM");
			trans.put("Reverb", "Reverb");
			trans.put("Depth", "Profundidad");
			trans.put("Mix Function", "Función");
			trans.put("Balance", "Equilibrio");
			trans.put("Bias", "Bias");
			trans.put("<<", "<<");
			trans.put("X Range", "X Intervalo");
			trans.put("X Type", "X Clase");
			trans.put("Y Range", "Y Intervalo");
			trans.put("Y Type", "Y Clase");
			trans.put("[+]", "[+]");
			trans.put("Continuous", "Continuo");
			trans.put("Chromatic", "Cromático");
			trans.put("Major", "Mayor");
			trans.put("Square", "Cuadrado");
			trans.put("Sawtooth", "Serrucho");
			trans.put("Triangle", "Triángulo");
			trans.put("Sine", "Seno");
			trans.put("Pulse", "Pulso");
			trans.put("Notch", "Muesca");
			trans.put("Add", "Añadir");
			trans.put("Subtract", "Sustraer");
			trans.put("Multiply", "Multiplicar");
			trans.put("Max", "Máximo");
			trans.put("Min", "Mínimo");
			trans.put("Linear", "Lineal");
			trans.put("Asymptotic", "Asintótica");
			trans.put("Save?", "¿Guardar?");
			trans.put("The instrument has changed.  Save it?", "El instrumento ha cambiado. ¿Guardalo?");
			trans.put("Discard", "Deseche");
			trans.put("Delay Level", "Nivel");
			trans.put("Delay Time", "Tiempo");
			trans.put("Cutoff", "Cortar");
			trans.put("Sample", "Muestra");
			trans.put("Select a WAV or SF2 file using", "Seleccione un archivo WAV o SF2 utilizando");
			trans.put("Crusher", "Trituradora");
			trans.put("Level", "Nivel");
			trans.put("Level 1", "Nivel 1");
			trans.put("Level 2", "Nivel 2");
			trans.put("Level 3", "Nivel 3");
			trans.put("Sample Rate", "Frecuencia de muestreo");
			trans.put("Quit and relaunch ModSynth to apply the change.", "Cierre y relanzar ModSynth para aplicar el cambio.");
			trans.put("Graph", "Gráfico");
			trans.put("Color icons to show output levels", "Iconos de color para mostrar los niveles de salida");

			trans.put("Arpeggiator", "Arpegiador");
			trans.put("Octaves", "Octavas");
			trans.put("Repeat", "Repetir");
			trans.put("Down Up", "Abajo Arriba");
			trans.put("Up Down", "Arriba Abajo");
			trans.put("Compressor", "Compresor");
			trans.put("Gain", "Aumento");
			trans.put("Length", "Duración");
			trans.put("Retrigger", "Redisparar");
			trans.put("Controls", "Controles");
			trans.put("Left", "Izquierda");
			trans.put("Right", "Derecha");
			trans.put("Unison", "Unísono");
			trans.put("Polyphony", "Polifonía");
			trans.put("SpectralFilter", "FiltroEspectral");
			trans.put("Frequency", "Frecuencia");
			trans.put("Freq Exp", "Frec Exp");
			trans.put("Random", "Aleatorio");
			trans.put("Custom", "Personalizado");
			trans.put("Positive", "Positivo");
			trans.put("Reverse Saw", "Serrucho Atrás");
			trans.put("Wave can only be edited in the full version of ModSynth.", "Wave sólo se puede editar en la versión completa de ModSynth.");
			trans.put("Harmonics can only be edited in the full version of ModSynth.", "Los armónicos sólo se pueden editar en la versión completa de ModSynth.");
			
			trans.put("Gate", "Puerta");
			trans.put("Phase", "Fase");
			trans.put("Scope", "Scopio");
			trans.put("In", "Ent");
			trans.put("Out", "Sal");
			trans.put("In 1", "Ent 1");
			trans.put("In 2", "Ent 2");
			trans.put("In 3", "Ent 3");
			trans.put("In L", "Ent Z");
			trans.put("Out L", "Sal Z");
			trans.put("In R", "Ent D");
			trans.put("Out R", "Sal D");
			trans.put("Clock", "Reloj");
			trans.put("Reset", "Reiniciar");
			trans.put("Audio", "Audio");
			trans.put("Glide", "Planeo");
			trans.put("Delay", "Retrasar");
			trans.put("Divider", "Divisor");
			trans.put("Divisor", "Divisor");
			trans.put("Duty", "Deber");
			trans.put("Controller", "Controlador");
			trans.put("Full version is needed to save this instrument.", "Se necesita una versión completa para guardar este instrumento.");
			trans.put("Full version is needed to edit this instrument.", "Se necesita una versión completa para editar este instrumento.");
			trans.put("Choose sample", "Elegir muestra");
			trans.put("SampleHold", "Retención");
			trans.put("Not enough memory to load this instrument.  Close other apps and try again.", "No hay suficiente memoria para cargar este instrumento. Cierre otras aplicaciones y vuelva a intentarlo.");
			trans.put("Gain",  "Ganancia");
			trans.put("Function", "Función");
			trans.put("LFO", "Oscilador Baja");
			trans.put("Legato", "Ligado");
			trans.put("Buffers", "Buffers");
			trans.put("Melody", "Melodía");
			trans.put("Pan", "Pan");
			trans.put("Distortion", "Distorsión");
			trans.put("Bypass", "Derivación");
			trans.put("Invert", "Invertir");
			trans.put("Run in background", "Ejecutar en segundo plano");
			trans.put("Load", "Carga");
			trans.put("could not be loaded.", "no pudo ser cargado.");
			trans.put("Version", "Versión");
			trans.put("Buffers", "Amortiguadores");
		}
		String transText = trans.get(text);
		return transText != null ? transText : super.translateSpanish(text);
	}

	@Override
	public String translateFrench(String text) {
		if (trans == null) {
			trans = new HashMap();
			trans.put("ModSynth", "ModSynth");
			trans.put("Synthesizer", "Synthétiseur");
			trans.put("polyphonic, modular, unlimited", "polyphonique, modulaire, illimité");
			
			// Translations for main panel
			trans.put("Instrument", "Instrument");
			trans.put("Sound", "Sonner");
			trans.put("Harmonics", "Harmoniques");
			trans.put("Filter", "Filtre");
			trans.put("Amp", "Amp");
			trans.put("Mod", "Mod");
			trans.put("Mod2", "Mod2");
			trans.put("Echo", "Echo");
			trans.put("Arpeggio", "Arpegio");
			trans.put("Sequencer", "Séquenceur");
			trans.put("Record", "Enregistrer");
			trans.put("Type", "Classe");
			trans.put("Shape", "Forme");
			trans.put("Amount", "Montant");
			trans.put("Rate", "Vitesse");
			trans.put("Sync", "Sync");
			trans.put("Attack", "Attaque");
			trans.put("Decay", " Déclin");
			trans.put("Sustain", "Soutenir");
			trans.put("Release", "Relâcher");
			trans.put("Save", "Enregistrez");
			trans.put("Save Recording", "Sauvegarder l'enregistrement");
			trans.put("Recording name:", "Nom d'enregistrement:");
			trans.put("Saved to", "Enregistré à");
			trans.put("Failed to save to", "Échec de l'enregistrement à");
			trans.put("Send", "Envoyer");
			trans.put("Delete", "Effacer");
			trans.put("Voices", "Voix");
			trans.put("Mono", "Mono");
			trans.put("Poly", "Poli");
			trans.put("Chorus", "Chorale");
			trans.put("Chorus Width", "Largeur Choir");
			trans.put("Portamento", "Portamento");
			trans.put("Velocity", "Vitesse");
			trans.put("Expression", "Expression");
			trans.put("Octave", "Octave");
			trans.put("Hold", "Tenier");
			trans.put("Key", "Touche");
			trans.put("Resonance", "Resonance");
			trans.put("Range", "Plage");
			trans.put("low", "faible");
			trans.put("high", "haut");
			trans.put("Volume", "Volume");
			trans.put("Overdrive", "Overdrive");
			trans.put("per Voice", "par voix");
			trans.put("Amount", "Montant");
			trans.put("Delay", "Retard");
			trans.put("Feedback", "Rétroaction");
			trans.put("Flange", "Bride");
			trans.put("Glide", "Glisser");
			trans.put("Note", "Nota");
			trans.put("Loop", "Boucle");
			trans.put("bpm", "bpm");
			trans.put("Up", "Haut");
			trans.put("Down", "Bas");
			trans.put("Stop", "Arrêtez");
			trans.put("Replay", "Rejouer");

			trans.put("None", "Rien");
			trans.put("Both", "Les deux");
			trans.put("Vibrato", "Vibrato");
			trans.put("Pitch", "Hauteur");
			trans.put("Volume+Filter", "Volume + Filtre");
			trans.put("C", "Do");
			trans.put("Db", "Ré bémol");
			trans.put("D", "Ré");
			trans.put("Eb", "Mi bémol");
			trans.put("E", "Mi");
			trans.put("F", "Fa");
			trans.put("Gb", "Sol bémol");
			trans.put("G", "Sol");
			trans.put("Ab", "La bémol");
			trans.put("A", "La");
			trans.put("Bb", "Si bémol");
			trans.put("B", "Si");
			trans.put("Low Pass", "Passe-bas");
			trans.put("Band Pass", "Passe-bande");
			trans.put("High Pass", "Passe-haut");
			trans.put("Fade", "Fade");
			trans.put("Comb 1", "Peigne 1");
			trans.put("Comb 2", "Peigne 2");
			trans.put("Comb 3", "Peigne 3");
			trans.put("Comb 4", "Peigne 4");
			trans.put("Formant 1", "Formant 1");
			trans.put("Formant 2", "Formant 2");
			trans.put("Formant 3", "Formant 3");
			trans.put("Formant 4", "Formant 4");
			trans.put("Wave", "Vague");
			trans.put("Ramp Up", "Rampe montante");
			trans.put("Ramp Down", "Rampe de descente");
			trans.put("Two Tone", "Deux tons");
			trans.put("Noise", "Bruit");
			trans.put("Pulse 1/4", "Pulse 1/4");
			trans.put("Pulse 1/8", "Pulse 1/8");
			trans.put("Pulse 1/16", "Pulse 1/16");
			trans.put("Mod Pitch", "Modifier hauteur");
			trans.put("Mod Amp", "Modifier l'amplitude");

			trans.put("Save sound as", "Enregistrer le son comme");
			trans.put("Delete sound?", "Supprimer le son?");
			trans.put("Are you sure you want to quit?", "Êtes-vous sûr de vouloir quitter?");
			trans.put("Save Recording", "Sauvegarder l'enregistrement");
			trans.put("Recording name:", "Nom de l'enregistrement:");

			// translations for settings panel
			trans.put("Settings", "Paramètres");
			trans.put("Keyboard size", "Taille du clavier");
			trans.put("Background", "Fond");
			trans.put("Choose", "Choisir");
			trans.put("MIDI channel", "MIDI canal");
			trans.put("Tuning type", "Classe de réglage");
			trans.put("Tuning cents", "Réglage fin");
			trans.put("Any", "Un canal");
			trans.put("Equal Temperament", "Tempérament égal");
			trans.put("Just Intonation", "Intonation juste");
			trans.put("Out of Tune", "Désaccordé");
			trans.put("Choose a background", "Choisir un fond");

			trans.put("Onyx", "Onyx");
			trans.put("Metal", "Métal");
			trans.put("Wood", "Bois");
			trans.put("Aura", "Aura");
			trans.put("Ice", "Glace");
			trans.put("Tea", "Thé");
			trans.put("Space", "Cosmos");
			trans.put("Sunset", "Coucher du soleil");
			trans.put("Tropical", "Tropical");

			// modsynth specific
			trans.put("Library", "Bibliothèque");
			trans.put("Get Full Version", "Obtenir la version complète");
			trans.put("Add Module", "ajouter le module");
			trans.put("Delete Module", "Supprimer le module");
			trans.put("Delete module?", "Supprimer le module?");
			trans.put("Edit", "éditer");
			trans.put("Edit >>", "éditer >>");
			trans.put("Start", "Lancer");
			trans.put("Done", "terminé");
			trans.put("No module selected.", "Aucun module sélectionné");
			trans.put("Full Version", "Version complète");
			trans.put("Add FM Operators, spectral filtering, PCM synthesis, harmonic editing and more with ModSynth full version!", 
					"Ajouter les opérateurs FM, le filtrage spectral, la synthèse PCM, l'édition harmonique et plus encore avec ModSynth version complète!");
			trans.put("Buy", "Acheter");
			trans.put("Later", "Annuler");
			trans.put("Sample rate", "Taux d'échantillonnage");
			trans.put("Tuning", "Réglage");
			trans.put("Wave Form", "Forme d'onde");
			trans.put(">>", ">>");
			trans.put("Detune", "Désaccorder");
			trans.put("Modulation", "Modulation");
			trans.put("<< Done", "<< Terminé");
			trans.put("on Glide", "Glissement");
			trans.put("Slope", "Pente");
			trans.put("Tone", "Ton");
			trans.put("Select module", "Sélection du module");
			trans.put("Envelope", "Enveloppe");
			trans.put("Mixer", "Mixer");
			trans.put("Oscillator", "Oscillateur");
			trans.put("Pad", "Bloc");
			trans.put("Keyboard", "Clavier");
			trans.put("Output", "Sortie");
			trans.put("Blue", "Bleu");
			trans.put("Green", "Vert");
			trans.put("Circuit", "Circuit");
			trans.put("Save instrument as", "Enregistrer instrument");
			trans.put("Delete instrument?", "Supprimer instrument?");
			trans.put("You cannot delete this instrument.", "Vous ne pouvez pas supprimer cet instrument.");
			trans.put("Operator", "Opérateur");
			trans.put("MultiOsc", "MultiOsc");
			trans.put("PCM", "PCM");
			trans.put("Reverb", "Réverb");
			trans.put("Depth", "Profondeur");
			trans.put("Mix Function", "Fonction");
			trans.put("Balance", "Balance");
			trans.put("Bias", "Bias");
			trans.put("<<", "<<");
			trans.put("X Range", "X Gamme");
			trans.put("X Type", "X Classe");
			trans.put("Y Range", "Y Gamme");
			trans.put("Y Type", "Y Classe");
			trans.put("[+]", "[+]");
			trans.put("Continuous", "Continu");
			trans.put("Chromatic", "Chromatique");
			trans.put("Major", "Grande");
			trans.put("Square", "Carrée");
			trans.put("Sawtooth", "Scie");
			trans.put("Triangle", "Triangle");
			trans.put("Sine", "Sinus");
			trans.put("Pulse", "Pouls");
			trans.put("Notch", "Entaille");
			trans.put("Add", "Additionner");
			trans.put("Subtract", "Soustraire");
			trans.put("Multiply", "Multiplier");
			trans.put("Max", "Maximum");
			trans.put("Min", "Minimum");
			trans.put("Linear", "Linéaire");
			trans.put("Asymptotic", "Asymp");
			trans.put("Save?", "Enregistrer?");
			trans.put("The instrument has changed.  Save it?", "L'instrument a changé . Sauve le?");
			trans.put("Discard", "Jeter");
			trans.put("Delay Level", "Niveau");
			trans.put("Delay Time", "Temps");
			trans.put("Cutoff", "Couper");
			trans.put("Sample", "échantillon");
			trans.put("Select a WAV or SF2 file using", "Sélectionnez un fichier WAV à l'aide");
			trans.put("Crusher", "Broyeur");
			trans.put("Level", "Niveau");
			trans.put("Level 1", "Niveau 1");
			trans.put("Level 2", "Niveau 2");
			trans.put("Level 3", "Niveau 3");
			trans.put("Sample Rate", "Taux d'échantillonnage");
			trans.put("Quit and relaunch ModSynth to apply the change.", "Quitter et relancer ModSynth pour appliquer le changement.");
			trans.put("Graph", "Graphique");
			trans.put("Color icons to show output levels", "Icônes de couleur pour afficher les niveaux de sortie");

			trans.put("Arpeggiator", "Arpégiateur");
			trans.put("Octaves", "Octaves");
			trans.put("Repeat", "Répéter");
			trans.put("Down Up", "Bas Haut");
			trans.put("Up Down", "Haut Bas");
			trans.put("Compressor", "Compresseur");
			trans.put("Gain", "Gain");
			trans.put("Length", "Durée");
			trans.put("Retrigger", "Redéclencher");
			trans.put("Controls", "Contrôles");
			trans.put("Left", "Gauche");
			trans.put("Right", "Droite");
			trans.put("Unison", "Unisson");
			trans.put("Polyphony", "Polyphonie");
			trans.put("SpectralFilter", "FiltreSpectral");
			trans.put("Frequency", "Fréquence");
			trans.put("Freq Exp", "Fréq Exp");
			trans.put("Random", "Aléatoire");
			trans.put("Custom", "Personnalisé");
			trans.put("Positive", "Positif");
			trans.put("Reverse Saw", "Scie Inverse");
			trans.put("Wave can only be edited in the full version of ModSynth.", "Wave ne peut être édité que dans la version complète de ModSynth.");
			trans.put("Harmonics can only be edited in the full version of ModSynth.", "Les harmoniques ne peuvent être édités que dans la version complète de ModSynth.");
		
			trans.put("Gate", "Porte");
			trans.put("Phase", "Phase");
			trans.put("Scope", "Scope");
			trans.put("In", "Ent");
			trans.put("Out", "Sor");
			trans.put("In 1", "Ent 1");
			trans.put("In 2", "Ent 2");
			trans.put("In 3", "Ent 3");
			trans.put("In L", "Ent G");
			trans.put("Out L", "Sor G");
			trans.put("In R", "Ent D");
			trans.put("Out R", "Sor D");
			trans.put("Clock", "Horloge");
			trans.put("Reset", "Réinitialiser");
			trans.put("Audio", "Audio");
			trans.put("Glide", "Glisser");
			trans.put("Delay", "Retard");
			trans.put("Divider", "Diviseur");
			trans.put("Divisor", "Diviseur");
			trans.put("Duty", "Devoir");
			trans.put("Controller", "Manette");
			trans.put("Full version is needed to save this instrument.", "La version complète est nécessaire pour sauvegarder cet instrument.");
			trans.put("Full version is needed to edit this instrument.", "La version complète est nécessaire pour éditer cet instrument.");
			trans.put("Choose sample", "Choisissez un échantillon");
			trans.put("SampleHold", "Retenue");
			trans.put("Not enough memory to load this instrument.  Close other apps and try again.", "Pas assez de mémoire pour charger cet instrument. Fermez les autres applications et réessayez.");
			trans.put("Gain",  "Gain");
			trans.put("Function", "Fonction");
			trans.put("LFO", "Oscillateur Faible");
			trans.put("Legato", "Ligado");
			trans.put("Buffers", "Buffers");
			trans.put("Melody", "Mélodie");
			trans.put("Pan", "Pan");
			trans.put("Distortion", "Distorsion");
			trans.put("Bypass", "Contourne");
			trans.put("Invert", "Inverser");
			trans.put("Run in background", "De fonctionner en arrière-plan");
			trans.put("Load", "Charge");
			trans.put("could not be loaded.", "n'a pas pu être chargé.");
			trans.put("Version", "Version");
			trans.put("Buffers", "Tampons");
		}
		String transText = trans.get(text);
		return transText != null ? transText : super.translateFrench(text);
	}

	@Override
	public String translateGerman(String text) {
		if (trans == null) {
			trans = new HashMap();
			trans.put("ModSynth", "ModSynth");
			trans.put("Synthesizer", "Synthétiseur");
			trans.put("polyphonic, modular, unlimited", "polyphon, modular, unbegrenzt");

			// Translations for main panel
			trans.put("Instrument", "Instrument");
			trans.put("Sound", "Klang");
			trans.put("Harmonics", "Harmonik");
			trans.put("Filter", "Filter");
			trans.put("Amp", "Amp");
			trans.put("Mod", "Mod");
			trans.put("Mod2", "Mod2");
			trans.put("Echo", "Echo");
			trans.put("Arpeggio", "Arpeggio");
			trans.put("Sequencer", "Sequenzer");
			trans.put("Record", "Aufnehmen");
			trans.put("Type", "Klasse");
			trans.put("Shape", "Form");
			trans.put("Amount", "Stärke");
			trans.put("Rate", "Rate");
			trans.put("Sync", "Sync");
			trans.put("Attack", "Anschwellzeit");
			trans.put("Decay", " Abklingzeit");
			trans.put("Sustain", "Dauerpegel");
			trans.put("Release", "Ausklingphase");
			trans.put("Save", "Speichern");
			trans.put("Save Recording", "Aufnahme speichern");
			trans.put("Recording name:", "Aufnahmename :");
			trans.put("Saved to", "gespeichert zu");
			trans.put("Failed to save to", "Fehler beim speichern");
			trans.put("Send", "Senden");
			trans.put("Delete", "Löschen");
			trans.put("Voices", "Stimmen");
			trans.put("Mono", "Mono");
			trans.put("Poly", "Poly");
			trans.put("Chorus", "Chor");
			trans.put("Chorus Width", "Chorbreite");
			trans.put("Portamento", "Portamento");
			trans.put("Velocity", "Dynamik ");
			trans.put("Expression", "Ausdruck");
			trans.put("Octave", "Oktave");
			trans.put("Hold", "Halten");
			trans.put("Key", "Schlüssel");
			trans.put("Resonance", "Resonanz");
			trans.put("Range", "Bereich");
			trans.put("low", "niedrig");
			trans.put("high", "hoch");
			trans.put("Volume", "Lautstärke");
			trans.put("Overdrive", "Übersteuerung");
			trans.put("per Voice", "pro Stimme");
			trans.put("Amount", "Höhe");
			trans.put("Delay", "Verzögerung");
			trans.put("Feedback", "Rückkopplung");
			trans.put("Flange", "Flansch");
			trans.put("Rate", "Rate");
			trans.put("Glide", "Gleiten");
			trans.put("Note", "Note");
			trans.put("Loop", "Schleife");
			trans.put("bpm", "bpm");
			trans.put("Up", "Oben");
			trans.put("Down", "Unten");
			trans.put("Record", "Aufnehmen");
			trans.put("Stop", "Stopp");
			trans.put("Replay", "Wiederholung");

			trans.put("None", "Keine");
			trans.put("Both", "Beide");
			trans.put("Vibrato", "Vibrato");
			trans.put("Pitch", "Tonhöhe");
			trans.put("Volume+Filter", "Volumen + Filter");
			trans.put("C", "C");
			trans.put("Db", "Des");
			trans.put("D", "D");
			trans.put("Eb", "Es");
			trans.put("E", "E");
			trans.put("F", "F");
			trans.put("Gb", "Ges");
			trans.put("G", "G");
			trans.put("Ab", "As");
			trans.put("A", "A");
			trans.put("Bb", "B");
			trans.put("B", "H");
			trans.put("Low Pass", "Tiefpass");
			trans.put("Band Pass", "Bandpass");
			trans.put("High Pass", "Hochpass");
			trans.put("Fade", "Ausblenden");
			trans.put("Comb 1", "Kamm 1");
			trans.put("Comb 2", "Kamm 2");
			trans.put("Comb 3", "Kamm 3");
			trans.put("Comb 4", "Kamm 4");
			trans.put("Formant 1", "Formanten 1");
			trans.put("Formant 2", "Formanten 2");
			trans.put("Formant 3", "Formanten 3");
			trans.put("Formant 4", "Formanten 4");
			trans.put("Wave", "Wellenform");
			trans.put("Ramp Up", "Rampe oben");
			trans.put("Ramp Down", "Rampe unten");
			trans.put("Two Tone", "Ton zwei");
			trans.put("Noise", "Rauschen");
			trans.put("Pulse 1/4", "Puls 1/4");
			trans.put("Pulse 1/8", "Puls 1/8");
			trans.put("Pulse 1/16", "Puls 1/16");
			trans.put("Mod Pitch", "Mod Ton");
			trans.put("Mod Amp", "Mod Amp");

			trans.put("Save sound as", "Klang speichern unter");
			trans.put("Delete sound?", "Klang löschen?");
			trans.put("Are you sure you want to quit?", "Sind Sie sicher, dass Sie aufhören wollen?");
			trans.put("Save Recording", "Aufnahme speichern");
			trans.put("Recording name:", "Aufzeichnung Namen:");

			// translations for settings panel
			trans.put("Settings", "Einstellungen");
			trans.put("Keyboard size", "Tastaturgröße");
			trans.put("Background", "Hintergrund");
			trans.put("Choose", "Wählen");
			trans.put("MIDI channel", "MIDI Kanal");
			trans.put("Tuning type", "Tuning- Klasse");
			trans.put("Tuning cents", "Feinabstimmung");
			trans.put("Any", "Irgendeiner");
			trans.put("Equal Temperament", "Gleichschwebende Stimmung");
			trans.put("Just Intonation", "Nur Intonation");
			trans.put("Out of Tune", "Verstimmt");
			trans.put("Choose a background", "Wählen Sie ein Hintergrund");
			trans.put("Onyx", "Onyx");
			trans.put("Metal", "Metall");
			trans.put("Wood", "Holz");
			trans.put("Aura", "Aura");
			trans.put("Ice", "Eis");
			trans.put("Tea", "Tee");
			trans.put("Space", "Weltraum");
			trans.put("Sunset", "Sonnenuntergang");
			trans.put("Tropical", "Tropisch");

			// modsynth specific
			trans.put("Library", "Bibliothek");
			trans.put("Get Full Version", "Erhalten Sie volle Version");
			trans.put("Add Module", "Modul hinzufügen");
			trans.put("Delete Module", "Modul löschen");
			trans.put("Delete module?", "Modul löschen?");
			trans.put("Edit", "Bearbeiten");
			trans.put("Edit >>", "Bearbeiten");
			trans.put("Start", "Starten");
			trans.put("Done", "Fertig");
			trans.put("No module selected.", "Kein Modul ausgewählt");
			trans.put("Full Version", "Vollversion");
			trans.put("Add FM Operators, spectral filtering, PCM synthesis, harmonic editing and more with ModSynth full version!", 
					"Add FM Operatoren, Spektralfilterung, PCM-Synthese, harmonische Bearbeitung und mehr mit ModSynth Vollversion!");
			trans.put("Buy", "Kaufen");
			trans.put("Later", "Später");
			trans.put("Sample rate", "Sample rate");
			trans.put("Tuning", "Tuning");
			trans.put("Wave Form", "Wellenform");
			trans.put(">>", ">>");
			trans.put("Detune", "Verstimmen");
			trans.put("Modulation", "Modulation");
			trans.put("<< Done", "<< Fertig");
			trans.put("on Glide", "auf glide");
			trans.put("Slope", "Steigung");
			trans.put("Tone", "Ton");
			trans.put("Select module", "Auswahlmodul");
			trans.put("Envelope", "Hüllkurve");
			trans.put("Mixer", "Mischer");
			trans.put("Oscillator", "Oszillator");
			trans.put("Pad", "Block");
			trans.put("Keyboard", "Tastatur");
			trans.put("Output", "Ausgang");
			trans.put("Blue", "Blau");
			trans.put("Green", "Grün");
			trans.put("Circuit", "Schaltung");
			trans.put("Save instrument as", "Instrument speichern unter");
			trans.put("Delete instrument?", "Instrument löschen?");
			trans.put("You cannot delete this instrument.", "Dieses Instrument kann nicht gelöscht werden.");
			trans.put("Operator", "Operator");
			trans.put("MultiOsc", "MehrOsz");
			trans.put("PCM", "PCM");
			trans.put("Reverb", "Nachhall");
			trans.put("Depth", "Tiefe");
			trans.put("Mix Function", "Mix -Funktion");
			trans.put("Balance", "Gleichgewicht");
			trans.put("Bias", "Verzerrung");
			trans.put("<<", "<<");
			trans.put("X Range", "X Bereich");
			trans.put("X Type", "X Klasse");
			trans.put("Y Range", "Y Bereich");
			trans.put("Y Type", "Y Klasse");
			trans.put("[+]", "[+]");
			trans.put("Continuous", "Dauer");
			trans.put("Chromatic", "Chromatisch");
			trans.put("Major", "Haupt");
			trans.put("Square", "Recheck");
			trans.put("Sawtooth", "Sägezahn");
			trans.put("Triangle", "Dreieck");
			trans.put("Sine", "Sinus");
			trans.put("Pulse", "Puls");
			trans.put("Notch", "Kerbe");
			trans.put("Add", "Addieren");
			trans.put("Subtract", "Subtrahieren");
			trans.put("Multiply", "Multiplizieren");
			trans.put("Max", "Maximum");
			trans.put("Min", "Minimum");
			trans.put("Linear", "Linear");
			trans.put("Asymptotic", "Asymp");
			trans.put("Save?", "Sparen?");
			trans.put("The instrument has changed.  Save it?", "Das Instrument hat sich geändert. Wollen Sie es speichern ?");
			trans.put("Discard", "Verwerfen");
			trans.put("Delay Level", "Verzögerungsstufe");
			trans.put("Delay Time", "Verzögerungszeit");
			trans.put("Cutoff", "Filterfrequenz");
			trans.put("Sample", "Audiodatei");
			trans.put("Select a WAV or SF2 file using", "Wählen Sie eine WAV -Datei mit");
			trans.put("Crusher", "Brecher");
			trans.put("Level", "Stufe");
			trans.put("Level 1", "Stufe 1");
			trans.put("Level 2", "Stufe 2");
			trans.put("Level 3", "Stufe 3");
			trans.put("Sample Rate", "Samplerate");
			trans.put("Quit and relaunch ModSynth to apply the change.", "Beenden und starten Sie ModSynth neu, um die Änderung zu übernehmen.");
			trans.put("Graph", "Graph");
			trans.put("Color icons to show output levels", "Farbsymbole zur Anzeige der Ausgangspegel");

			trans.put("Arpeggiator", "Arpeggiator");
			trans.put("Octaves", "Oktaven");
			trans.put("Repeat", "Wiederholen");
			trans.put("Down Up", "Unten Oben");
			trans.put("Up Down", "Oben Unten");
			trans.put("Compressor", "Kompressor");
			trans.put("Gain", "Gewinn");
			trans.put("Length", "Länge");
			trans.put("Retrigger", "Retrigger");
			trans.put("Controls", "Steuerungen");
			trans.put("Left", "Links");
			trans.put("Right", "Recht");
			trans.put("Unison", "Einklang");
			trans.put("Polyphony", "Polyfonie");
			trans.put("SpectralFilter", "Spektralfilter");
			trans.put("Frequency", "Frequenz");
			trans.put("Freq Exp", "Freq Exp");
			trans.put("Random", "Zufällig");
			trans.put("Custom", "Personalisiert");
			trans.put("Positive", "Positiv");
			trans.put("Reverse Saw", "Reverse Sägezahn");
			trans.put("Wave can only be edited in the full version of ModSynth.", "Wave kann nur in der Vollversion von ModSynth bearbeitet werden.");
			trans.put("Harmonics can only be edited in the full version of ModSynth.", "Harmonics können nur in der Vollversion von ModSynth bearbeitet werden.");
			
			trans.put("Gate", "Tor");
			trans.put("Phase", "Phase");
			trans.put("Scope", "Skop");
			trans.put("In", "Ein");
			trans.put("Out", "Aus");
			trans.put("In 1", "Ein 1");
			trans.put("In 2", "Ein 2");
			trans.put("In 3", "Ein 3");
			trans.put("In L", "Ein L");
			trans.put("Out L", "Aus L");
			trans.put("In R", "Ein R");
			trans.put("Out R", "Aus R");
			trans.put("Clock", "Uhr");
			trans.put("Reset", "Neustart");
			trans.put("Audio", "Audio");
			trans.put("Glide", "Gleiten");
			trans.put("Delay", "Verzögern");
			trans.put("Divider", "Divider");
			trans.put("Divisor", "Divisor");
			trans.put("Duty", "Pflichtig");
			trans.put("Controller", "Regler");
			trans.put("Full version is needed to save this instrument.", "Vollversion ist erforderlich, um dieses Instrument zu speichern.");
			trans.put("Full version is needed to edit this instrument.", "Vollversion wird benötigt, um dieses Instrument zu bearbeiten.");
			trans.put("Choose sample", "Wähle Probe");
			trans.put("SampleHold", "SampleHold");
			trans.put("Not enough memory to load this instrument.  Close other apps and try again.", "Nicht genug Speicher, um dieses Instrument zu laden. Schließen Sie andere Apps und versuchen Sie es erneut.");
			trans.put("Gain",  "Gewinn");
			trans.put("Function", "Funktion");
			trans.put("LFO", "Geringer Osz");
			trans.put("Legato", "Legato");
			trans.put("Buffers", "Buffers");
			trans.put("Soft Clip", "Weicher Clip");
			trans.put("Melody", "Melodie");
			trans.put("Pan", "Pan");
			trans.put("Distortion", "Verzerrung");
			trans.put("Bypass", "Bypass");
			trans.put("Invert", "Umkehren");
			trans.put("Run in background", "Im Hintergrund laufen");
			trans.put("Load", "Belastung");
			trans.put("could not be loaded.", "konnte nicht geladen werden.");
			trans.put("Version", "Version");
			trans.put("Buffers", "Puffer");
		}
		String transText = trans.get(text);
		return transText != null ? transText : super.translateGerman(text);
	}

	@Override
	public String translateRussian(String text) {
		if (trans == null) {
			trans = new HashMap();
			trans.put("ModSynth", "ModSynth");
			trans.put("Synthesizer", "Синтезатор");
			trans.put("polyphonic, modular, unlimited", "полифонический, модульный, неограниченный");

			// translations for main panel
			trans.put("Instrument", "инструмент");
			trans.put("Sound", "звук");
			trans.put("Harmonics", "Гармоники");
			trans.put("Filter", "фильтр");
			trans.put("Amp", "ампер");
			trans.put("Mod", "мод");
			trans.put("Mod2", "мод2");
			trans.put("Echo", "эхо");
			trans.put("Arpeggio", "арпеджио");
			trans.put("Sequencer", "секвенсор");
			trans.put("Record", "запись");
			trans.put("Type", "Класс");
			trans.put("Shape", "форма");
			trans.put("Amount", "Количество");
			trans.put("Rate", "Ставка");
			trans.put("Sync", "Синх");
			trans.put("Attack", "Атака");
			trans.put("Decay", "распад");
			trans.put("Save", "Сохранить");
			trans.put("Save Recording", "Сохранить запись");
			trans.put("Recording name:", "Запись имя :");
			trans.put("Saved to", "Добавлено в");
			trans.put("Failed to save to", "не удалось сохранить");
			trans.put("Send", "послать");
			trans.put("Delete", "Удалить");
			trans.put("Voices", "Голоса");
			trans.put("Mono", "моно");
			trans.put("Poly", "Поли");
			trans.put("Chorus", "хор");
			trans.put("Chorus Width", "Ширина хора");
			trans.put("Portamento", "принимая");
			trans.put("Velocity", "скорость");
			trans.put("Expression", "выражение");
			trans.put("Octave", "октава");
			trans.put("Hold", "Держать");
			trans.put("Key", "ключ");
			trans.put("Resonance", "резонанс");
			trans.put("Range", "Ассортимент");
			trans.put("low", "низкий");
			trans.put("high", "высокая");
			trans.put("Attack", "Атака");
			trans.put("Decay", "распад");
			trans.put("Sustain", "поддерживать");
			trans.put("Release", "Выпуск");
			trans.put("Volume", "объем");
			trans.put("Overdrive", "овердрайв");
			trans.put("per Voice", "за голоса");
			trans.put("Shape", "форма");
			trans.put("Amount", "Количество");
			trans.put("Rate", "Ставка");
			trans.put("Sync", "Синх");
			trans.put("Delay", "задержка");
			trans.put("Feedback", "Обратная связь");
			trans.put("Flange", "фланец");
			trans.put("Glide", "скольжение");
			trans.put("Note", "Заметка");
			trans.put("Loop", "петля");
			trans.put("bpm", "Чтм");
			trans.put("Up", "вверх");
			trans.put("Down", "вниз");
			trans.put("Record", "запись");
			trans.put("Stop", "Стоп");
			trans.put("Replay", "переигровка");
			trans.put("Save", "Сохранить");

			trans.put("None", "Ни одной");
			trans.put("Both", "И то и другое");
			trans.put("Vibrato", "вибрато");
			trans.put("Pitch", "Подача");
			trans.put("Volume+Filter", "Громкость + фильтр");
			trans.put("C", "До");
			trans.put("Db", "Ре-бемоль");
			trans.put("D", "Ре");
			trans.put("Eb", "Ми-бемоль");
			trans.put("E", "Ми");
			trans.put("F", "Фа");
			trans.put("Gb", "Соль-бемоль");
			trans.put("G", "Соль");
			trans.put("Ab", "Ля-бемоль");
			trans.put("A", "Ля");
			trans.put("Bb", "Си-бемоль");
			trans.put("B", "Си");
			trans.put("Low Pass", "Низкий Проходить");
			trans.put("Band Pass", "Группа Проходить");
			trans.put("High Pass", "Высокая Проходить");
			trans.put("Fade", "увядать");
			trans.put("Comb 1", "гребень 1");
			trans.put("Comb 2", "гребень 2");
			trans.put("Comb 3", "гребень 3");
			trans.put("Comb 4", "гребень 4");
			trans.put("Formant 1", "формант 1");
			trans.put("Formant 2", "формант 2");
			trans.put("Formant 3", "формант 3");
			trans.put("Formant 4", "формант 4");
			trans.put("Wave", "Волна");
			trans.put("Ramp Up", "Нарастить");
			trans.put("Ramp Down", "Замедления");
			trans.put("Two Tone", "Две тонны");
			trans.put("Noise", "Шум");
			trans.put("Pulse 1/4", "Пульс 1/4");
			trans.put("Pulse 1/8", "Пульс 1/8");
			trans.put("Pulse 1/16", "Пульс 1/16");
			trans.put("Mod Pitch", "мод Подача");
			trans.put("Mod Amp", "мод ампер");

			trans.put("Save sound as", "Сохранить звук");
			trans.put("Delete sound?", "Удалить звук ?");
			trans.put("Are you sure you want to quit?", "Вы уверены, что хотите выйти?");
			trans.put("Save Recording", "Сохранить запись");
			trans.put("Recording name:", "Запись имя:");

			// translations for settings
			trans.put("Settings", "настройки");
			trans.put("Keyboard size", "размер клавиатуры");
			trans.put("Background", "Задний план");
			trans.put("Choose", "Выберите");
			trans.put("MIDI channel", "MIDI канал");
			trans.put("Tuning type", "класс тюнинг");
			trans.put("Tuning cents", "Тюнинг центов");
			trans.put("Any", "Любой канал");
			trans.put("Equal Temperament", "Равно Темперамент");
			trans.put("Just Intonation", "Просто Интонация");
			trans.put("Out of Tune", "Расстроенный");
			trans.put("Choose a background", "Выберите фон");
			trans.put("Onyx", "оникс");
			trans.put("Metal", "металл");
			trans.put("Wood", "Дерево");
			trans.put("Aura", "аура");
			trans.put("Ice", "лед");
			trans.put("Tea", "Чай");
			trans.put("Space", "Космос");
			trans.put("Sunset", "Закат солнца");
			trans.put("Tropical", "тропический");

			// modsynth specific
			trans.put("Library", "библиотека");
			trans.put("Get Full Version", "Получить полную версию");
			trans.put("Add Module", "Добавить модуль");
			trans.put("Delete Module", "Удалить модуль");
			trans.put("Delete module?", "Удалить модуль?");
			trans.put("Edit", "редактировать");
			trans.put("Edit >>", "редактировать");
			trans.put("Start", "Запуск");
			trans.put("Done", "Завершен");
			trans.put("No module selected.", "Модуль не выбран");
			trans.put("Full Version", "Полная версия");
			trans.put("Add FM Operators, spectral filtering, PCM synthesis, harmonic editing and more with ModSynth full version!", 
					"Добавить FM-операторы, спектральную фильтрацию, синтез PCM, редактирование гармоник и многое другое с полной версией ModSynth!");
			trans.put("Buy", "купить");
			trans.put("Later", "Позже");
			trans.put("Sample rate", "Частота дискретизации");
			trans.put("Tuning", "настройка");
			trans.put("Wave Form", "Форма волны");
			trans.put(">>", ">>");
			trans.put("Detune", "расстраивать");
			trans.put("Modulation", "модуляция");
			trans.put("<< Done", "<< Готово");
			trans.put("on Glide", "скольжение");
			trans.put("Slope", "наклон");
			trans.put("Tone", "тон");
			trans.put("Select module", "Выберите модуль");
			trans.put("Envelope", "конверт");
			trans.put("Mixer", "Смеситель");
			trans.put("Oscillator", "генератор");
			trans.put("Pad", "блокнот");
			trans.put("Keyboard", "клавиатура");
			trans.put("Output", "Вывод");
			trans.put("Blue", "синий");
			trans.put("Green", "зеленый");
			trans.put("Circuit", "схема");
			trans.put("Save instrument as", "Сохранить инструмент, как");
			trans.put("Delete instrument?", "Удалить инструмент?");
			trans.put("You cannot delete this instrument.", "Вы не можете удалить этот инструмент.");
			trans.put("Operator", "оператор");
			trans.put("MultiOsc", "несколько ген");
			trans.put("PCM", "PCM");
			trans.put("Reverb", "реверб");
			trans.put("Depth", "глубина");
			trans.put("Mix Function", "функция");
			trans.put("Balance", "Баланс");
			trans.put("Bias", "смещение");
			trans.put("<<", "<<");
			trans.put("X Range", "X дальность");
			trans.put("X Type", "X класс");
			trans.put("Y Range", "Y дальность");
			trans.put("Y Type", "Y класс");
			trans.put("[+]", "[+]");
			trans.put("Continuous", "непрерывный");
			trans.put("Chromatic", "Хроматическая");
			trans.put("Major", "мажорный");
			trans.put("Square", "квадрат");
			trans.put("Sawtooth", "пила");
			trans.put("Triangle", "треугольник");
			trans.put("Sine", "синус");
			trans.put("Pulse", "Пульс");
			trans.put("Notch", "паз");
			trans.put("Add", "Добавить");
			trans.put("Subtract", "вычитать");
			trans.put("Multiply", "Умножьте");
			trans.put("Max", "максимум");
			trans.put("Min", "минимум");
			trans.put("Linear", "линейный");
			trans.put("Asymptotic", "асимп");
			trans.put("Save?", "Сохрани?");
			trans.put("The instrument has changed.  Save it?", "Прибор изменилось . Сохрани это?");
			trans.put("Discard", "сбрасывать");
			trans.put("Delay Level", "уровень");
			trans.put("Delay Time", "время");
			trans.put("Cutoff", "Отрезать");
			trans.put("Sample", "Образец");
			trans.put("Select a WAV or SF2 file using", "Выберите WAV файл, используя");
			trans.put("Crusher", "дробилка");
			trans.put("Level", "уровень");
			trans.put("Level 1", "уровень 1");
			trans.put("Level 2", "уровень 2");
			trans.put("Level 3", "уровень 3");
			trans.put("Sample Rate", "Частота дискретизации");
			trans.put("Quit and relaunch ModSynth to apply the change.", "Закройте и перезапустите ModSynth, чтобы применить изменение.");
			trans.put("Graph", "график");
			trans.put("Color icons to show output levels", "Цветные значки, чтобы показать выходные уровни");

			trans.put("Arpeggiator", "арпеджиатор");
			trans.put("Octaves", "октавы");
			trans.put("Repeat", "Повторение");
			trans.put("Down Up", "вниз вверх");
			trans.put("Up Down", "вверх вниз");
			trans.put("Compressor", "компрессор");
			trans.put("Gain", "Усиление");
			trans.put("Length", "длина");
			trans.put("Retrigger", "триггер");
			trans.put("Controls", "управления");
			trans.put("Left", "левая");
			trans.put("Right", "правая");
			trans.put("Unison", "унисон");
			trans.put("Polyphony", "Полифония");
			trans.put("SpectralFilter", "спектралфильтр");
			trans.put("Frequency", "частота");
			trans.put("Freq Exp", "частота мощ");
			trans.put("Random", "случайный");
			trans.put("Custom", "персонализ");
			trans.put("Positive", "плюс");
			trans.put("Reverse Saw", "обратный пила");
			trans.put("Wave can only be edited in the full version of ModSynth.", "Волна может быть отредактирован только в полной версии ModSynth.");
			trans.put("Harmonics can only be edited in the full version of ModSynth.", "Гармоники могут быть изменены только в полной версии ModSynth.");
			
			trans.put("Gate", "Ворота");
			trans.put("Phase", "фаза");
			trans.put("Scope", "граф");
			trans.put("In", "вхо");
			trans.put("Out", "Выхо");
			trans.put("In 1", "вхо 1");
			trans.put("In 2", "вхо 2");
			trans.put("In 3", "вхо 3");
			trans.put("In L", "вхо Л");
			trans.put("Out L", "Выхо Л");
			trans.put("In R", "вхо Н");
			trans.put("Out R", "Выхо Н");
			trans.put("Clock", "Часы");
			trans.put("Reset", "сброс");
			trans.put("Audio", "аудио");
			trans.put("Glide", "Планер");
			trans.put("Delay", "задержка");
			trans.put("Divider", "делитель");
			trans.put("Divisor", "делитель");
			trans.put("Duty", "причина");
			trans.put("Controller", "контроллер");
			trans.put("Full version is needed to save this instrument.", "Для сохранения этого инструмента необходима полная версия.");
			trans.put("Full version is needed to edit this instrument.", "Для редактирования этого инструмента необходима полная версия.");
			trans.put("Choose sample", "Выберите образец");
			trans.put("SampleHold", "Держать");
			trans.put("Not enough memory to load this instrument.  Close other apps and try again.", "Недостаточно памяти для загрузки этого инструмента. Закройте другие приложения и повторите попытку.");
			trans.put("Gain",  "усиление");
			trans.put("Function", "функция");
			trans.put("LFO", "низкий ген");
			trans.put("Legato", "Легато");
			trans.put("Buffers", "Buffers");
			trans.put("Soft Clip", "Софт клип");
			trans.put("Melody", "Мелодия");
			trans.put("Pan", "Пан");
			trans.put("Distortion", "Искажение");
			trans.put("Bypass", "байпас");
			trans.put("Invert", "Инвертировать");
			trans.put("Run in background", "Запустить в фоновом режиме");
			trans.put("Load", "Нагрузка");
			trans.put("could not be loaded.", "не удалось загрузить.");
			trans.put("Version", "Версия");
			trans.put("Buffers", "Буферы");
		}
		String transText = trans.get(text);
		return transText != null ? transText : super.translateRussian(text);
	}

}
